Improve a way of handling inactive app in the channel
saleor/saleor-taxjar pull request #8
Opened 2022-08-05 11:43 UTC by korycins

Improve a way of handling app inactive in the channel.
- add validations to webhook handler to confirm that taxjar configuration is provided & it is active
- add valdiation to not be able saving Taxjar configuration as an active, without providing API key

2022-08-05 11:44 UTC, korycins commented on backend/utils.ts
> +  let message = "";
Any idea if I can do this better? Assuming that in the future I could have more checks here (`if`s)

2022-08-17 08:12 UTC, bmigirl requested changes

2022-08-17 08:12 UTC, bmigirl commented on backend/metaHandlers.ts
> +      ([_, configuration]) =>
I think you can even remove `_`
```suggestion
      ([, configuration]) =>
```

2022-08-17 08:12 UTC, bmigirl commented on backend/metaHandlers.ts
> +    .map(([channelSlug, _]) => channelSlug);
```suggestion
    .map(([channelSlug]) => channelSlug);
```

2022-08-17 08:12 UTC, bmigirl commented on backend/utils.ts
> +  let message = "";
I'd say 
```
export const taxJarConfigIsValidToUse = (taxJarConfig: TaxJarConfig) => {
  const defaultResponse = {
    isValid: true,
    status: 200,
  };

  if (!taxJarConfig.active) {
    console.log("TaxJar is not active.");

    return {
      ...defaultResponse,
      message: "TaxJar is not active.",
      isValid: false,
    };
```

etc.

2022-08-17 08:39 UTC, merged